SAMPLES = glob_wildcards("raw_reads/{sample}_1.fastq.gz").sample

rule all:
    input:
        expand("results/{sample}_1_fastqc.html", sample=SAMPLES),
        expand("results/{sample}_2_fastqc.html", sample=SAMPLES),
        expand("results/{sample}.bam", sample=SAMPLES),
        expand("results/{sample}.bam.bai", sample=SAMPLES)

rule fastqc:
    input:
        "raw_reads/{sample}_1.fastq.gz",
        "raw_reads/{sample}_2.fastq.gz"
    output:
        "results/{sample}_1_fastqc.html",
        "results/{sample}_2_fastqc.html"
    shell:
        """
        fastqc {input} -o results
        """

rule align:
    input:
        r1="raw_reads/{sample}_1.fastq.gz",
        r2="raw_reads/{sample}_2.fastq.gz"
    output:
        "results/{sample}.bam"
    shell:
        """
        hisat2 -x reference/chr22_index \
        -1 {input.r1} \
        -2 {input.r2} | \
        samtools sort -o {output}
        """

rule index_bam:
    input:
        "results/{sample}.bam"
    output:
        "results/{sample}.bam.bai"
    shell:
        """
        samtools index {input}
        """
